"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HelloWorlds__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HelloWorlds__factory_1 = require("./HelloWorlds__factory");
Object.defineProperty(exports, "HelloWorlds__factory", { enumerable: true, get: function () { return HelloWorlds__factory_1.HelloWorlds__factory; } });
