/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloWorlds } from "./HelloWorlds";
export * as factories from "./factories";
export { HelloWorlds__factory } from "./factories/HelloWorlds__factory";
