/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multichain } from "./Multichain";
export * as factories from "./factories";
export { Multichain__factory } from "./factories/Multichain__factory";
